name: Build Container

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: login to docker registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        tags: ghcr.io/randomnumber:${{ github.run_number }}
        push: true
